### ISSUE TITLE
Hello, Roberto, can you provide Linux 64 version?

### ISSUE THREAD

**Issue by pony5551** [RDP1974/Delphi64#1]
it‘s me! pony5551：）are you ok?

**Comment by RDP1974** [comment]
all ok, you?

Linux64 version of? Intel TBB IPP layers?

**Comment by pony5551** [comment]
Everything is fine!



Yes, I need Intel TBB IPP for Linux 64！

**Comment by RDP1974** [comment]
I'm too busy now to do it. Will notify eventually next weeks.

**Comment by pony5551** [comment]
B: thank you. I'm in no hurry,

Now the new crown pneumonia, I hope you protect yourself and your family and friends!

**Comment by RDP1974** [comment]
thanks for your kind words, cu soon

**Comment by RDP1974** [comment]
Hello,
IMHO we don't need Intel LIBS on Linux because:
- DCC64 performs greatly under Linux without FastMM4 
- Linux low level mem functions are optimized
I did a test with apachebench n1000 c100 against Debian8 Apache2.4 mod webbroker and IIS10 2006 webbroker + RDP Intel patches (8 core I9):
results are very similar, 10.000 request x second both IIS Windows and Linux Apache

**Comment by pony5551** [comment]
Thanks for your advice
